baseURL: https://www.iaxy.in/
languageCode: en-us
title: Akshay Vadher
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

# googleAnalytics: UA-176281983-1
# googleAnalytics: G-8N0SWGD0Y1

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Akshay Vadher
  description: "Akshay Vadher personal"
  keywords: [Blog, Portfolio, Akshay]
  author: Akshay Vadher
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon_io/favicon.ico"
    favicon16x16: "favicon_io/favicon-16x16.png"
    favicon32x32: "favicon_io/favicon-32x32.png"
    apple_touch_icon: "favicon_io/apple-touch-icon.png"
    safari_pinned_tab: "favicon_io/favicon.ico"

  label:
    text: "Home"
    # icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Akshay Vadher
    subtitle: "Personal Blog"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Akshay
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hey \U0001F928"
    Content: I vent Technology and Personal thoughts here

  socialIcons:
    - name: github
      url: "https://github.com/akshayvadher"
    - name: linkedin
      url: https://www.linkedin.com/in/akshayvadher/
    - name: stackoverflow
      url: "https://stackoverflow.com/users/1534925/akshay"
    - name: youtube
      url: https://www.youtube.com/c/AkshayVadher
    - name: instagram
      url: https://www.instagram.com/akshayvadher/
    - name: twitter
      url: "https://twitter.com/akshay_vadher"
    - name: goodreads
      url: "https://www.goodreads.com/akshayvadher"
    - name: Incubyte Blog
      url: "https://engineering.incubyte.co/authors/akshay-vadher/"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/akshayvadher/akshayvadher.github.io/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: tech-category
      name: Tech
      url: /categories/tech
      weight: 10
    - identifier: personal-category
      name: Personal
      url: /categories/personal
      weight: 20
    - name: Search
      url: search/
      weight: 30
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 40
    - name: About Me
      url: about-me/
      weight: 50
    - name: Now
      url: now/
      weight: 60

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
